apiVersion: apps/v1
kind: Deployment
metadata:
  name: superadmin
  labels:
    app: superadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superadmin
  template:
    metadata:
      annotations:
        rollout: "2026-09-22-staff-management-interactive-v1"
      labels:
        app: superadmin
    spec:
      containers:
      - name: superadmin
        image: ttl.sh/transhola-superadmin-2026:24h
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: NODE_OPTIONS
          value: "--max-http-header-size=262144"
        - name: SUPABASE_INTERNAL_URL
          value: "http://supabase-kong:8000"
        - name: NEXT_PUBLIC_SUPABASE_URL
          value: "http://supabase-kong:8000"
        - name: NEXT_PUBLIC_SUPABASE_ANON_KEY
          value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0"
        - name: SUPABASE_SERVICE_ROLE_KEY
          value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: superadmin-service
spec:
  selector:
    app: superadmin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: superadmin-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: admin.transhola.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: superadmin-service
            port:
              number: 80
